/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Components;

import GUI.EvacSimMainFrame;

/**
 *
 * @author hector
 */
public class camControls extends javax.swing.JPanel {

    private SidePanel  sidepanel;
    private EvacSimMainFrame mainframe;
    /**
     * Creates new form camControls
     */
    public camControls() {
        initComponents();
        mainframe = null;
    }
    
    public void passParents(SidePanel  p, EvacSimMainFrame m) {
        mainframe = m;
        sidepanel = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        camSpeed = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        panRight = new javax.swing.JButton();
        panLeft = new javax.swing.JButton();
        panUp = new javax.swing.JButton();
        panDown = new javax.swing.JButton();
        mLeft = new javax.swing.JButton();
        mRight = new javax.swing.JButton();
        mDown = new javax.swing.JButton();
        mUp = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(280, 280));
        setMinimumSize(new java.awt.Dimension(280, 280));
        setPreferredSize(new java.awt.Dimension(280, 280));

        camSpeed.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        camSpeed.setForeground(new java.awt.Color(246, 244, 242));
        camSpeed.setMaximum(15);
        camSpeed.setMinimum(1);
        camSpeed.setValue(8);
        camSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                camSpeedStateChanged(evt);
            }
        });

        jLabel1.setText("Cam Speed");

        panRight.setText("Pan Right");
        panRight.setMaximumSize(new java.awt.Dimension(95, 30));
        panRight.setMinimumSize(new java.awt.Dimension(95, 30));
        panRight.setPreferredSize(new java.awt.Dimension(95, 30));

        panLeft.setText("Pan Left");
        panLeft.setMaximumSize(new java.awt.Dimension(95, 30));
        panLeft.setMinimumSize(new java.awt.Dimension(95, 30));
        panLeft.setPreferredSize(new java.awt.Dimension(95, 30));

        panUp.setToolTipText("Pan Up");

        panDown.setToolTipText("Pan Down");

        mLeft.setText("Left");
        mLeft.setMaximumSize(new java.awt.Dimension(95, 30));
        mLeft.setMinimumSize(new java.awt.Dimension(95, 30));
        mLeft.setPreferredSize(new java.awt.Dimension(95, 30));

        mRight.setText("Right");
        mRight.setMaximumSize(new java.awt.Dimension(95, 30));
        mRight.setMinimumSize(new java.awt.Dimension(95, 30));
        mRight.setPreferredSize(new java.awt.Dimension(95, 30));

        mDown.setToolTipText("Move Down");
        mDown.setMaximumSize(new java.awt.Dimension(30, 95));
        mDown.setMinimumSize(new java.awt.Dimension(30, 95));
        mDown.setPreferredSize(new java.awt.Dimension(30, 75));

        mUp.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        mUp.setToolTipText("Move Up");
        mUp.setMaximumSize(new java.awt.Dimension(30, 95));
        mUp.setMinimumSize(new java.awt.Dimension(30, 95));
        mUp.setPreferredSize(new java.awt.Dimension(30, 75));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(camSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panDown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(96, 96, 96))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(97, 97, 97)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(camSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panUp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panDown, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void camSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_camSpeedStateChanged
        if (mainframe != null) {
            mainframe.setCamSpeed(camSpeed.getValue());
        }
    }//GEN-LAST:event_camSpeedStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider camSpeed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mDown;
    private javax.swing.JButton mLeft;
    private javax.swing.JButton mRight;
    private javax.swing.JButton mUp;
    private javax.swing.JButton panDown;
    private javax.swing.JButton panLeft;
    private javax.swing.JButton panRight;
    private javax.swing.JButton panUp;
    // End of variables declaration//GEN-END:variables
}
